

app:
  url: http://localhost:3000

otp:
  secret: 26Etz0ZMoBmiX7F9lHvb

jws:
  secret: 6f97ca1e5fdf4a418bf0ad0badd33dd716f63e7f593a4b7f9e4b4304316fd09a

oauth2:
  client:
    id: 646977083886-0hbur7doj5r5p6jmcs0k2qd3akhk5cns.apps.googleusercontent.com
    secret: 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
  auth:
    url: https://accounts.google.com/o/oauth2/v2/auth
  token:
    url: https://oauth2.googleapis.com/token
  redirect:
    url: http://localhost:3000/auth/google/callback

jwt:
  privateKeyFilePath: classpath:keys/privateJwt-key.pem
  publicKeyFilePath: classpath:keys/publicJwt-key.pem
  expiration: 1

refreshToken:
  privateKeyFilePath: classpath:keys/privateRefresh-key.pem
  publicKeyFilePath: classpath:keys/publicRefresh-key.pem
  expiration: 24


login:
  maxAttempts: 3
  timeOut: 300

account:
  removeUnverifiedAccountAfterHours: 24
  deactivateAccountAfterDays: 31

transaction:
  timeout: 8


admin:
  datasource:
    jdbcUrl: jdbc:postgresql://db:5432/landlordkingdom
    driver-class-name: org.postgresql.Driver
    username: landlordkingdomadmin
    password: adminP@ssw0rd
    transaction-isolation: TRANSACTION_READ_COMMITTED
    auto-commit: false

spring:
  task:
    scheduling:
      pool:
        size: 5
  mail:
    host: smtp4dev
    port: 25
    username: user
    password: user
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
server:
  servlet:
    context-path: /api