services:
  db:
    image: postgres:16.2-alpine
    container_name: landlordkingdom-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - my_network
    volumes:
      - ./initDb.sql:/docker-entrypoint-initdb.d/init.sql
#      - ./initDb.sql:/docker-entrypoint-initdb.d/init2.sql

  tomcat:
    build:
      context: ..
      dockerfile: docker/DockerfileTomcat
    container_name: landlordkingdom-tomcat
    restart: always
    ports:
      - "8080:8080"
    networks:
      - my_network
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - db

#  nginx:
#    image: nginx:1.21.3
#    container_name: landlordkingdom-nginx
#    restart: always
#    ports:
#      - "9090:80"
#    networks:
#      - my_network
#    volumes:
#      - ./nginxdev.conf:/etc/nginx/nginx.conf

  smtp4dev:
    image: rnwood/smtp4dev
    container_name: smtp4dev
    restart: always
    ports:
      - "5000:80"
      - "25:25"
    networks:
      - my_network

networks:
  my_network:
